version: '3'

services:
  vue:
    container_name: front
    build: .
    ports:
      - "8080:8080"
    working_dir: /app
    tty: true
    volumes:
      - ../protoc-gen-docker/src/ts:/app/src/pb
      - ./app/helloworld-front:/app/
#     networks:
#       - helloworld-server_default
# networks:
#   helloworld-server_default:
#     external: true